### ISSUE TITLE
error on install "developer" field unallowed

### ISSUE THREAD

**Issue by vsmelov** [adrianmarinwork/ChatgptToPdf#1]
<img width="1440" alt="Screenshot 2023-04-14 at 21 03 16" src="https://user-images.githubusercontent.com/9407507/232066836-3e5dd2f8-8e01-462a-97bc-2f00c2fd7a8e.png">

**Comment by adrianmarinwork** [comment]
Looks like the key "developer" is not supported in Chrome, I'll get rid of it.
The fix to this problem will be available in the next version.
Thank you!
